[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

# Make custom option cycles work on right direction
[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''focused.children[3]:click()'''
position = "after"
payload = '''
if focused.config.focus_args.handy_cycle then
    focused.children[5]:click()
end
'''
match_indent = true


# Custom movement control
[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''if focused.config.focus_args.type == 'cycle' and input_type == 'press' then'''
position = "before"
payload = '''
if (focused.config.focus_args.type == 'handy_dictionary_item' or focused.config.focus_args.handy_cycle) and input_type == 'press' then
    local proto_choices = focused.UIBox:get_group(nil, focused.config.focus_args.handy_group or focused.config.group)
    local choices = {}
    for k, v in ipairs(proto_choices) do
        if (v.config.button or v.config.hover or v == focused) and (not v.config.focus_args or v.config.focus_args.type ~= "none") then choices[#choices+1] = v end
    end
    -- print("custom focus arg", focused.config.focus_args.handy_group or focused.config.group, button, #choices)

    for k, v in ipairs(choices) do
        if v == focused then
            -- print("Focused", k)
            if (button == 'triggerleft') then 
                local next_i = k ~= 1 and (k-1) or (#choices)
                if focused.config.focus_args.no_loop and next_i > k then ret = nil
                else
                    self:snap_to({node = choices[next_i]})
                    self:update_cursor()
                    ret = true
                end
            elseif (button == 'triggerright') then 
                local next_i = k ~= #choices and (k+1) or (1)
                if focused.config.focus_args.no_loop and next_i < k then ret = nil
                else
                    self:snap_to({node = choices[next_i]})
                    self:update_cursor()
                    ret = true
                end
            end
            break
        else
        end
    end
end
'''
match_indent = true


# Correct focus movement on hand selection preview


[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''if nu_rank ~= self.focused.target.rank then G.ARGS.focus_list[1] = {node = G.hand.cards[nu_rank]} end'''
position = "after"
payload = '''
elseif Handy.UI.data.hand_selection_preview_area and (dir == 'L' or dir == 'R') and self.focused.target and self.focused.target:is(Card) and self.focused.target.area == Handy.UI.data.hand_selection_preview_area then 
    local handy_area = Handy.UI.data.hand_selection_preview_area
    local nu_rank = self.focused.target.rank + (dir == 'L' and -1 or 1)
    if nu_rank > #handy_area.cards then nu_rank = 1 end
    if nu_rank == 0 then nu_rank = #handy_area.cards end
    if nu_rank ~= self.focused.target.rank then G.ARGS.focus_list[1] = {node = handy_area.cards[nu_rank]} end
'''
match_indent = true


# Prevent button pip crash
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local BUTTON_SPRITE = Sprite(0,0,args.scale or 0.45,args.scale or 0.45,G.ASSET_ATLAS["gamepad_ui"],'''
position = "before"
payload = '''
if not args.button or not button_sprite_map[args.button] then
    return {
        n = G.UIT.ROOT,
        config = { align = "cm", colour = G.C.CLEAR },
        nodes = {
            { n = G.UIT.O, config = { object = Moveable() } },
        },
    }
end
'''
match_indent = true


# Add ability to override chosen tab in create_tabs
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''if v.chosen then args.current = {k = k, v = v} end'''
position = "before"
payload = '''
if Handy.override_create_tabs_chosen then v.chosen = k == Handy.override_create_tabs_chosen
elseif Handy.override_create_tabs_chosen_by_label then v.chosen = v.label == Handy.override_create_tabs_chosen_by_label end
'''
match_indent = true


# Insert speed multiplier and animation skip in vanilla settings
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''create_option_cycle({w = 5, label = localize('b_set_play_discard_pos'),scale = 0.8, options = localize('ml_play_discard_pos_opt'), opt_callback = 'change_play_discard_position', current_option = (G.SETTINGS.play_button_pos)}),'''
position = "before"
payload = '''
Handy.UI.settings_speed_multiplier(),
Handy.UI.settings_animation_skip(),
'''
match_indent = true


# Add own timer for UI in config menu
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''self.TIMERS.TOTAL = self.TIMERS.TOTAL + dt*(self.SPEEDFACTOR)'''
position = "after"
payload = '''
self.TIMERS.HANDY_TOTAL = (self.TIMERS.HANDY_TOTAL or 0) + self.real_dt*(self.SPEEDFACTOR)
'''
match_indent = true

# Custom DynaText pop_in duration
[[patches]]
[patches.pattern]
target = "engine/text.lua"
pattern = '''if self.config.pop_out then'''
position = "at"
payload = '''
if self.config.handy_pop_in_duration then
    local prev_pop_in = letter.pop_in
    local time_letter_exist = G.TIMERS.REAL - (self.config.pop_in or 0) - self.created_time
    letter.pop_in = time_letter_exist*#self.string / self.config.handy_pop_in_duration - k + 1
    letter.pop_in = math.min(1, math.max(letter.pop_in, self.config.min_cycle_time == 0 and 1 or 0))
    if prev_pop_in <=0 and letter.pop_in > 0 and not self.silent and
    (#self.string < 10 or k%2 == 0) then
        if self.T.x > G.ROOM.T.w+2 or
        self.T.y > G.ROOM.T.h+2 or
        self.T.x <-2 or
        self.T.y <-2 then else
            play_sound('paper1', 0.45+0.05*math.random()+(0.3/#self.string)*k + (self.config.pitch_shift or 0))
        end
    end
    if k == #self.strings[self.focused_string].letters and letter.pop_in >= 1 then
        if #self.strings > 1 then
            self.pop_delay = (G.TIMERS.REAL - self.config.pop_in - self.created_time + (self.config.pop_delay or 1.5))
            self:pop_out(4)
        else
            self.config.pop_in = nil
        end
    end
elseif self.config.pop_out then
'''
match_indent = true
