Handy.controls.stacks = {
	keyboard = {
		op = "first",
		{
			op = "first",
			"presets_switch_load_1",
			"presets_switch_load_2",
			"presets_switch_load_3",
			"presets_switch_load_next",
		},
		{
			op = "first",
			{
				op = "any",
				"speed_multiplier_toggle_temp_disabled",
				"animation_skip_toggle_temp_disabled",
			},
			{
				op = "any",
				"speed_multiplier_increase",
				"animation_skip_increase",
			},
			{
				op = "any",
				"speed_multiplier_decrease",
				"animation_skip_decrease",
			},
		},
		{
			op = "first",
			{
				op = "first",
				"insta_actions",
			},
			{
				op = "first",
				"hand_selection_insta_highlight",
				"hand_selection_deselect_hand",
				"hand_selection_entire_f_hand",
			},
			{
				op = "first",
				"regular_keybinds_change_sort_rank",
				"regular_keybinds_change_sort_suit",
				"regular_keybinds_toggle_sort",
			},
			{
				op = "first",
				"regular_keybinds_discard",
				"regular_keybinds_play",
				"regular_keybinds_not_just_yet_interaction",
			},
			{
				op = "first",
				"regular_keybinds_cash_out",
				"regular_keybinds_skip_booster",
				"regular_keybinds_reroll_shop",
				"regular_keybinds_leave_shop",
			},
			{
				op = "first",
				"regular_keybinds_reroll_boss",
				"regular_keybinds_skip_blind",
				"regular_keybinds_select_blind",
			},
			{
				op = "first",
				"move_highlight_one_left",
				"move_highlight_one_right",
			},
			{
				op = "first",
				"regular_keybinds_run_info",
				"regular_keybinds_run_info_binds",
				"regular_keybinds_view_deck",
				"regular_keybinds_view_lobby_info",
				"regular_keybinds_mod_settings",
			},
			{
				op = "first",
				"misc_crash",
				"misc_quick_restart",
				"misc_save_run",
				"misc_start_fantoms_preview",
			},
			{
				op = "first",
				"dangerous_actions_sell_one",
				"dangerous_actions_remove_one",
				"dangerous_actions_sell_all_same",
				"dangerous_actions_remove_all_same",
				"dangerous_actions_sell_all",
				"dangerous_actions_remove_all",
			},
		},
	},
	mouse = {
		op = "first",
		{
			op = "first",
			"presets_switch_load_1",
			"presets_switch_load_2",
			"presets_switch_load_3",
			"presets_switch_load_next",
		},
		{
			op = "first",
			{
				op = "any",
				"speed_multiplier_toggle_temp_disabled",
				"animation_skip_toggle_temp_disabled",
			},
			{
				op = "any",
				"speed_multiplier_increase",
				"animation_skip_increase",
			},
			{
				op = "any",
				"speed_multiplier_decrease",
				"animation_skip_decrease",
			},
		},
		{
			op = "first",
			{
				op = "first",
				"insta_actions",
			},
			{
				op = "first",
				"hand_selection_insta_highlight",
				"hand_selection_deselect_hand",
				"hand_selection_entire_f_hand",
			},
			{
				op = "first",
				"regular_keybinds_change_sort_rank",
				"regular_keybinds_change_sort_suit",
				"regular_keybinds_toggle_sort",
			},
			{
				op = "first",
				"regular_keybinds_discard",
				"regular_keybinds_play",
				"regular_keybinds_not_just_yet_interaction",
			},
			{
				op = "first",
				"regular_keybinds_cash_out",
				"regular_keybinds_skip_booster",
				"regular_keybinds_reroll_shop",
				"regular_keybinds_leave_shop",
			},
			{
				op = "first",
				"regular_keybinds_reroll_boss",
				"regular_keybinds_skip_blind",
				"regular_keybinds_select_blind",
			},
			{
				op = "first",
				"move_highlight_one_left",
				"move_highlight_one_right",
			},
			{
				op = "first",
				"regular_keybinds_run_info",
				"regular_keybinds_run_info_binds",
				"regular_keybinds_view_deck",
				"regular_keybinds_view_lobby_info",
				"regular_keybinds_mod_settings",
			},
			{
				op = "first",
				"misc_crash",
				"misc_quick_restart",
				"misc_save_run",
				"misc_start_fantoms_preview",
			},
			{
				op = "first",
				"dangerous_actions_sell_one",
				"dangerous_actions_remove_one",
				"dangerous_actions_sell_all_same",
				"dangerous_actions_remove_all_same",
				"dangerous_actions_sell_all",
				"dangerous_actions_remove_all",
			},
		},
	},
	wheel = {
		op = "first",
		{
			op = "first",
			"presets_switch_load_1",
			"presets_switch_load_2",
			"presets_switch_load_3",
			"presets_switch_load_next",
		},
		{
			op = "first",
			{
				op = "any",
				"speed_multiplier_toggle_temp_disabled",
				"animation_skip_toggle_temp_disabled",
			},
			{
				op = "any",
				"speed_multiplier_increase",
				"animation_skip_increase",
			},
			{
				op = "any",
				"speed_multiplier_decrease",
				"animation_skip_decrease",
			},
		},
		{
			op = "first",
			{
				op = "first",
				"insta_actions",
			},
			{
				op = "first",
				"hand_selection_insta_highlight",
				"hand_selection_deselect_hand",
				"hand_selection_entire_f_hand",
			},
			{
				op = "first",
				"regular_keybinds_change_sort_rank",
				"regular_keybinds_change_sort_suit",
				"regular_keybinds_toggle_sort",
			},
			{
				op = "first",
				"regular_keybinds_discard",
				"regular_keybinds_play",
				"regular_keybinds_not_just_yet_interaction",
			},
			{
				op = "first",
				"regular_keybinds_cash_out",
				"regular_keybinds_skip_booster",
				"regular_keybinds_reroll_shop",
				"regular_keybinds_leave_shop",
			},
			{
				op = "first",
				"regular_keybinds_reroll_boss",
				"regular_keybinds_skip_blind",
				"regular_keybinds_select_blind",
			},
			{
				op = "first",
				"move_highlight_one_left",
				"move_highlight_one_right",
			},
			{
				op = "first",
				"regular_keybinds_run_info",
				"regular_keybinds_run_info_binds",
				"regular_keybinds_view_deck",
				"regular_keybinds_view_lobby_info",
				"regular_keybinds_mod_settings",
			},
			{
				op = "first",
				"misc_crash",
				"misc_quick_restart",
				"misc_save_run",
				"misc_start_fantoms_preview",
			},
			{
				op = "first",
				"dangerous_actions_sell_one",
				"dangerous_actions_remove_one",
				"dangerous_actions_sell_all_same",
				"dangerous_actions_remove_all_same",
				"dangerous_actions_sell_all",
				"dangerous_actions_remove_all",
			},
		},
	},
	gamepad = {
		op = "first",
		{
			op = "first",
			"presets_switch_load_1",
			"presets_switch_load_2",
			"presets_switch_load_3",
			"presets_switch_load_next",
		},
		{
			op = "first",
			{
				op = "any",
				"speed_multiplier_toggle_temp_disabled",
				"animation_skip_toggle_temp_disabled",
			},
			{
				op = "any",
				"speed_multiplier_increase",
				"animation_skip_increase",
			},
			{
				op = "any",
				"speed_multiplier_decrease",
				"animation_skip_decrease",
			},
		},
		{
			op = "first",
			{
				op = "first",
				"insta_actions",
			},
			{
				op = "first",
				"hand_selection_insta_highlight",
				"hand_selection_deselect_hand",
				"hand_selection_entire_f_hand",
			},
			{
				op = "first",
				"regular_keybinds_change_sort_rank",
				"regular_keybinds_change_sort_suit",
				"regular_keybinds_toggle_sort",
			},
			{
				op = "first",
				"regular_keybinds_discard",
				"regular_keybinds_play",
				"regular_keybinds_not_just_yet_interaction",
			},
			{
				op = "first",
				"regular_keybinds_cash_out",
				"regular_keybinds_skip_booster",
				"regular_keybinds_reroll_shop",
				"regular_keybinds_leave_shop",
			},
			{
				op = "first",
				"regular_keybinds_reroll_boss",
				"regular_keybinds_skip_blind",
				"regular_keybinds_select_blind",
			},
			{
				op = "first",
				"regular_keybinds_run_info",
				"regular_keybinds_run_info_binds",
				"regular_keybinds_view_deck",
				"regular_keybinds_view_lobby_info",
				"regular_keybinds_mod_settings",
			},
			{
				op = "first",
				"misc_crash",
				"misc_quick_restart",
				"misc_save_run",
				"misc_start_fantoms_preview",
			},
			{
				op = "first",
				"dangerous_actions_sell_one",
				"dangerous_actions_remove_one",
				"dangerous_actions_sell_all_same",
				"dangerous_actions_remove_all_same",
				"dangerous_actions_sell_all",
				"dangerous_actions_remove_all",
			},
		},
	},

	card_hover = {
		op = "first",
		"hand_selection_insta_highlight",
		"dangerous_actions_sell_one",
		"dangerous_actions_remove_one",
	},
	card_click = {
		op = "first",
		"dangerous_actions_sell_all_same",
		"dangerous_actions_remove_all_same",
		"dangerous_actions_sell_all",
		"dangerous_actions_remove_all",
		"insta_actions",
	},
	tag_hover = {
		op = "first",
		"dangerous_actions_remove_one",
	},
	tag_click = {
		op = "first",
		"dangerous_actions_remove_all_same",
		"dangerous_actions_remove_all",
	},
}

-- TODO: gamepad

Handy.load_files({
	"speed_multiplier.lua",
	"animation_skip.lua",
	"presets_switch.lua",
	"hand_selection.lua",
	"scoring_hold.lua",
	"regular_keybinds.lua",
	"move_highlight.lua",
	"misc.lua",
	"controller_sensitivity.lua",
	"insta_actions.lua",
	"dangerous_actions.lua",
}, "src/controls/all/")
