name: Thunderstore Upload

on:
    push:
        tags:
            - '*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: GreenTF/upload-thunderstore-package@v4.3
              with:
                  namespace: SleepyG11
                  description: Quality of Life controls and keybinds for Balatro
                  token: ${{ secrets.THUNDERSTORE_API_KEY }}
                  name: Handy
                  version: ${{ github.ref_name }}
                  community: balatro
                  repo: thunderstore.io
                  categories: |
                      mods
